[readable]
cv_imshow_title = Collision Avoidance with Mantis Shrimp Eyes
ustunekayit_true_ayriayri_false = True
ana_dataset = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/
output_path_folder = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/outputs/
models_path_folder = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/models/
dnn_dataset = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/dnn_dataset/
siamese_dataset = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/siamese_dataset/
yolo_dataset = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/yolo_dataset/
right_detection_model = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/models/yolo/best_420_1024.pt
dnn_rnn_dataset = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/rnn_dataset/
dnn_distance_model = model_20230316-164852
rnn_trajectory_model_folder = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/models/rnn/

[changeable]
threshold = 0.7
video_path_file = ../../Datasets/Mantis-Shrimp-Eye-s-Collision-Avoidance/videos/train\02a8b666e30848c890d719c8c37ade9b.mp4

